In [44]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [45]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [46]:
m = np.zeros((3,3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [47]:
a = np.random.randint(1, 11, (5, 5))
print(a)

[[ 1  6  2  3  9]
 [ 1  3  5  3  3]
 [ 5 10  9  6  3]
 [10  2  3 10  7]
 [ 1  3  4  9  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [58]:
a = np.random.random((4, 4))
print(a)

[[0.09453949 0.01424534 0.51992333 0.88915996]
 [0.13139905 0.86516524 0.62777319 0.39078183]
 [0.72332725 0.26532063 0.34023781 0.64873882]
 [0.27177602 0.77550043 0.63515112 0.5437497 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [49]:
a = np.random.randint(1, 11, 5)
print('a = ', a)
b = np.random.randint(1, 11, 5)
print('b = ', b)
print('a + b = ', a + b)
print('a - b = ', a - b)
print('a * b = ', a * b)

a =  [6 1 9 7 2]
b =  [ 4  3 10  8  1]
a + b =  [10  4 19 15  3]
a - b =  [ 2 -2 -1 -1  1]
a * b =  [24  3 90 56  2]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [50]:
a = np.random.random(7)
print('a = ', a)
b = np.random.random(7)
print('b = ', b)
print('(a, b) = ', np.dot(a, b))

a =  [0.6972419  0.60338471 0.88033393 0.80363968 0.6564765  0.7019297
 0.44470997]
b =  [0.90189408 0.0615027  0.74458222 0.36074439 0.34098279 0.54479718
 0.56664566]
(a, b) =  2.469587131158354


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [54]:
a = np.random.randint(1, 11, (2, 2))
print('A = ', a)
b = np.random.randint(1, 11, (2, 3))
print('B = ', b)
print('A * B = ', np.dot(a, b))

A =  [[5 7]
 [6 1]]
B =  [[7 4 8]
 [9 8 3]]
A * B =  [[98 76 61]
 [51 32 51]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [56]:
a = np.random.randint(1, 11, (3, 3))
print('A = ', a)
print('A^(-1) = ', np.linalg.inv(a))

A =  [[ 6 10  2]
 [ 4  8  2]
 [ 6  9  8]]
A^(-1) =  [[ 0.88461538 -1.19230769  0.07692308]
 [-0.38461538  0.69230769 -0.07692308]
 [-0.23076923  0.11538462  0.15384615]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [60]:
a = np.random.random((4, 4))
print('A = ', a)
print('A^T = ', a.T)

A =  [[0.46312311 0.52196655 0.49952799 0.09335109]
 [0.15845859 0.20928609 0.84981852 0.616244  ]
 [0.62016131 0.84318736 0.6695211  0.09167773]
 [0.41838761 0.03350085 0.20584901 0.82222421]]
A^T =  [[0.46312311 0.15845859 0.62016131 0.41838761]
 [0.52196655 0.20928609 0.84318736 0.03350085]
 [0.49952799 0.84981852 0.6695211  0.20584901]
 [0.09335109 0.616244   0.09167773 0.82222421]]


10. Cтворіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [64]:
a = np.random.randint(1, 11, (3, 4))
print('A = ', a)
b = np.random.randint(1, 11, 4)
print('b = ', b)
print('A * b = ', np.dot(a, b))

A =  [[ 7 10  1  5]
 [ 5  9  7  2]
 [ 3  8  3  9]]
b =  [8 1 4 7]
A * b =  [105  91 107]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [66]:
a = np.random.random((2, 3))
print('A = ', a)
b = np.random.random(3)
print('b = ', b)
print('A * b = ', np.dot(a, b))

A =  [[0.51200301 0.43116845 0.1506974 ]
 [0.26501506 0.95026893 0.67388477]]
b =  [0.27054689 0.41361792 0.78974896]
A * b =  [0.43587293 0.99694705]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [68]:
a = np.random.randint(1, 11, (2, 2))
print('A = ', a)
b = np.random.randint(1, 11, (2, 2))
print('B = ', b)
print('A * B = ', a * b)

A =  [[1 2]
 [1 5]]
B =  [[8 9]
 [9 3]]
A * B =  [[ 8 18]
 [ 9 15]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [69]:
a = np.random.randint(1, 11, (2, 2))
print('A = ', a)
b = np.random.randint(1, 11, (2, 2))
print('B = ', b)
print('A * B = ', np.dot(a, b))

A =  [[5 8]
 [5 2]]
B =  [[3 2]
 [2 4]]
A * B =  [[31 42]
 [19 18]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [71]:
a = np.random.randint(1, 101, (5, 5))
print('A = ', a)
print('el_sum = ', a.sum())

A =  [[17 98 81 81 31]
 [85  2 44 23 85]
 [94  4 79  2 68]
 [29 78 75 15 71]
 [67 40 19 26 10]]
el_sum =  1224


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [74]:
a = np.random.randint(1, 11, (4, 4))
print('A = ', a)
b = np.random.randint(1, 11, (4, 4))
print('B = ', b)
print('A - B = ', a - b)

A =  [[ 7  7  6  1]
 [ 4 10  9  9]
 [ 8  7  9  5]
 [ 1  3  5  8]]
B =  [[ 2  1 10  5]
 [ 8  7  2  4]
 [ 8 10  6  8]
 [ 2  1  7  9]]
A - B =  [[ 5  6 -4 -4]
 [-4  3  7  5]
 [ 0 -3  3 -3]
 [-1  2 -2 -1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [79]:
a = np.random.random((3, 3))
print('A = ', a)
print('sums = ', (np.sum(a, axis=1)).reshape(-1, 1))

A =  [[0.30739906 0.14632202 0.07576672]
 [0.79775108 0.83222098 0.74649387]
 [0.03235211 0.35206564 0.22778752]]
sums =  [[0.5294878 ]
 [2.37646592]
 [0.61220527]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [86]:
a = np.random.randint(1, 100, (4, 4))
print('A = ', a)
print('A ^ 2 = ', np.square(a))

A =  [[93 96 56 89]
 [61 57 30 28]
 [18 16 72  1]
 [78 10 33 36]]
A ^ 2 =  [[8649 9216 3136 7921]
 [3721 3249  900  784]
 [ 324  256 5184    1]
 [6084  100 1089 1296]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [88]:
a = np.random.randint(1, 51, 4)
print('a = ', a)
print('sqrt(a) = ', np.sqrt(a))

a =  [ 2 46  2 18]
sqrt(a) =  [1.41421356 6.78232998 1.41421356 4.24264069]
